# Generated by Django 4.0.3 on 2022-04-12 13:50

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
                ('made_type', model_utils.fields.StatusField(choices=[('Handmade', 'Handmade'), ('Machine', 'Machine')], default='Handmade', max_length=100, no_check_for_status=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='ConsumerElectronic',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
                ('consumer_type', model_utils.fields.StatusField(choices=[('TV', 'TV'), ('Security Camera', 'Security Camera'), ('Vacuum Cleaners', 'Vacuum Cleaners'), ('Refrigerator', 'Refrigerator'), ('Freezer', 'Freezer'), ('Oven', 'Oven'), ('Microwave', 'Microwave'), ('Toaster', 'Toaster'), ('DishWasher', 'DishWasher'), ('Washing Machine', 'Washing Machine'), ('Dryer', 'Dryer'), ('Coffee Maker', 'Coffee Maker'), ('Blender', 'Blender'), ('Mixer', 'Mixer'), ('Iron', 'Iron'), ('Conditioner', 'Conditioner'), ('Other', 'Other')], default='TV', max_length=100, no_check_for_status=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='DishesAppliances',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
                ('good_type', model_utils.fields.StatusField(choices=[('Dish', 'Dish'), ('Appliance', 'Appliance')], default='Dish', max_length=100, no_check_for_status=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
                ('furniture_type', model_utils.fields.StatusField(choices=[('Bed', 'Bed'), ('Sofas', 'Sofas'), ('Armchair', 'Armchair'), ('Cabinet', 'Cabinet'), ('Table', 'Table'), ('Shelving', 'Shelving'), ('Chair', 'Chair'), ('Stand', 'Stand'), ('Computer Table', 'Computer Table'), ('Kitchen Set', 'Kitchen Set'), ('Book Case', 'Book Case'), ('Bedside Table', 'Bedside Table'), ('Other', 'Other')], default='Bed', max_length=100, no_check_for_status=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
                ('plant_type', models.CharField(max_length=55)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='home_garden/plant_images/')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_images', to='home_garden.plant')),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='home_garden/furniture_images/')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_images', to='home_garden.furniture')),
            ],
        ),
        migrations.CreateModel(
            name='DishesAppliancesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='home_garden/dishes_images/')),
                ('dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes_images', to='home_garden.dishesappliances')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerElectronicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='home_garden/consumer_e_images/')),
                ('consumer_electronic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cons_images', to='home_garden.consumerelectronic')),
            ],
        ),
        migrations.CreateModel(
            name='CarpetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='home_garden/carpet_images/')),
                ('carpet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpet_images', to='home_garden.carpet')),
            ],
        ),
    ]
