# Generated by Django 4.0.3 on 2022-04-12 13:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', model_utils.fields.StatusField(choices=[('Aşgabat', 'Aşgabat'), ('Lebap welaýaty', 'Lebap welaýaty'), ('Darganata', 'Darganata'), ('Farap', 'Farap'), ('Gazojak', 'Gazojak'), ('Dänew', 'Dänew'), ('Garabekewül', 'Garabekewül'), ('Türkmenabat', 'Türkmenabat'), ('Dostluk', 'Dostluk'), ('Hojambaz', 'Hojambaz'), ('Köýtendag', 'Köýtendag'), ('Kerki', 'Kerki'), ('Magdanly', 'Magdanly'), ('Sakar', 'Sakar'), ('Saýat', 'Saýat'), ('Seýdi', 'Seýdi'), ('Çärjew', 'Çärjew'), ('Halaç', 'Halaç'), ('Ahal welaýaty', 'Ahal welaýaty'), ('Ýaşlyk', 'Ýaşlyk'), ('Ak bugdaý etraby', 'Ak bugdaý etraby'), ('Bäherden', 'Bäherden'), ('Babadaýhan', 'Babadaýhan'), ('Gökdepe', 'Gökdepe'), ('Kaka', 'Kaka'), ('Änew', 'Änew'), ('Tejen', 'Tejen'), ('Sarahs', 'Sarahs'), ('Balkan welaýaty', 'Balkan welaýaty'), ('Magtymguly', 'Magtymguly'), ('Bereket', 'Bereket'), ('Etrek', 'Etrek'), ('Esenguly', 'Esenguly'), ('Gumdag', 'Gumdag'), ('Balkanabat', 'Balkanabat'), ('Garabogaz', 'Garabogaz'), ('Hazar', 'Hazar'), ('Serdar', 'Serdar'), ('Türkmenbaşy', 'Türkmenbaşy'), ('Jebel', 'Jebel'), ('Mary welaýaty', 'Mary welaýaty'), ('Ýolöten', 'Ýolöten'), ('Mary', 'Mary'), ('Murgap', 'Murgap'), ('Sakarçäge', 'Sakarçäge'), ('Serhetabat ', 'Serhetabat '), ('Tagtabazar', 'Tagtabazar'), ('Türkmengala', 'Türkmengala'), ('Oguz han', 'Oguz han'), ('Baýramaly', 'Baýramaly'), ('Şatlyk', 'Şatlyk'), ('Wekilbazar', 'Wekilbazar'), ('Garagum etraby', 'Garagum etraby'), ('Daşoguz welaýaty', 'Daşoguz welaýaty'), ('Akdepe', 'Akdepe'), ('Gurbansoltan Eje', 'Gurbansoltan Eje'), ('Boldumsaz', 'Boldumsaz'), ('Daşoguz', 'Daşoguz'), ('Gubadag', 'Gubadag'), ('Görogly(Tagta)', 'Görogly(Tagta)'), ('Türkmenbaşy etraby', 'Türkmenbaşy etraby'), ('Ruhubelent etraby', 'Ruhubelent etraby'), ('Köneürgenç', 'Köneürgenç'), ('S.A. Nyýazow etr', 'S.A. Nyýazow etr')], default='Aşgabat', max_length=100, no_check_for_status=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('currency_type', model_utils.fields.StatusField(choices=[('TMT', 'TMT'), ('USD', 'USD')], default='TMT', max_length=100, no_check_for_status=True)),
                ('phone_num', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('extra_phone_num', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
