# Generated by Django 4.0.3 on 2022-04-12 13:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estate', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
                ('sell_type', model_utils.fields.StatusField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], default='Sell', max_length=100, no_check_for_status=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('estate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estate.estate')),
                ('room', models.IntegerField(blank=True, null=True)),
                ('floor_type', model_utils.fields.StatusField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('9+', '9+')], default='1', max_length=100, no_check_for_status=True)),
                ('square', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('estate.estate',),
        ),
        migrations.CreateModel(
            name='CottageHouse',
            fields=[
                ('estate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estate.estate')),
                ('room', models.IntegerField(blank=True, null=True)),
                ('floor_type', model_utils.fields.StatusField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('9+', '9+')], default='1', max_length=100, no_check_for_status=True)),
                ('square', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('square_type', model_utils.fields.StatusField(choices=[('M2', 'M2'), ('SOT', 'SOT'), ('GA', 'GA')], default='M2', max_length=100, no_check_for_status=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('estate.estate',),
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('estate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estate.estate')),
                ('square', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('square_type', model_utils.fields.StatusField(choices=[('M2', 'M2'), ('SOT', 'SOT'), ('GA', 'GA')], default='M2', max_length=100, no_check_for_status=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('estate.estate',),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('estate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estate.estate')),
                ('room', models.IntegerField(blank=True, null=True)),
                ('floor_type', model_utils.fields.StatusField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('9+', '9+')], default='1', max_length=100, no_check_for_status=True)),
                ('square', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('estate.estate',),
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('estate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estate.estate')),
                ('room', models.IntegerField(blank=True, null=True)),
                ('floor_type', model_utils.fields.StatusField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('9+', '9+')], default='1', max_length=100, no_check_for_status=True)),
                ('square', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('square_type', model_utils.fields.StatusField(choices=[('M2', 'M2'), ('SOT', 'SOT'), ('GA', 'GA')], default='M2', max_length=100, no_check_for_status=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('estate.estate',),
        ),
        migrations.CreateModel(
            name='WorkPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='estate/workplace_images/')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace_images', to='estate.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='estate/office_images/')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_images', to='estate.office')),
            ],
        ),
        migrations.CreateModel(
            name='LandPlotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='estate/land_plot_images/')),
                ('land_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_plot_images', to='estate.landplot')),
            ],
        ),
        migrations.AddField(
            model_name='cottagehouseimage',
            name='cottage_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cottage_house_images', to='estate.cottagehouse'),
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_images', to='estate.apartment'),
        ),
    ]
