# Generated by Django 4.0.3 on 2022-04-12 13:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
                ('brand_type', model_utils.fields.StatusField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Chery', 'Chery'), ('Chevrolet', 'Chevrolet'), ('Citroen', 'Citroen'), ('Chrysler', 'Chrysler'), ('DAF', 'DAF'), ('Daewoo', 'Daewoo'), ('Dodge', 'Dodge'), ('Ford', 'Ford'), ('Forland', 'Forland'), ('Fekon', 'Fekon'), ('Fiat', 'Fiat'), ('Geely', 'Geely'), ('Honda', 'Honda'), ('Howo', 'Howo'), ('Hyundai', 'Hyundai'), ('Infiniti', 'Infiniti'), ('Iveco', 'Iveco'), ('Isuzu', 'Isuzu'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('JCB', 'JCB'), ('Kamaz', 'Kamaz'), ('KIA', 'KIA'), ('Land Rover', 'Land Rover'), ('Lada', 'Lada'), ('Lexus', 'Lexus'), ('Mazda', 'Mazda'), ('MAN', 'MAN'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Opel', 'Opel'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Skoda', 'Skoda'), ('Scania', 'Scania'), ('SsangYong', 'SsangYong'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Toyota', 'Toyota'), ('Tofas', 'Tofas'), ('Tesla', 'Tesla'), ('UAZ', 'UAZ'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('WAZ', 'WAZ'), ('GAZ', 'GAZ'), ('Yamaha', 'Yamaha'), ('Zil', 'Zil'), ('Other', 'Other')], default='Audi', max_length=100, no_check_for_status=True)),
                ('sell_type', model_utils.fields.StatusField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], default='Sell', max_length=100, no_check_for_status=True)),
                ('year_type', model_utils.fields.StatusField(choices=[('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], default='1980', max_length=100, no_check_for_status=True)),
                ('color', models.CharField(max_length=55)),
                ('credit', models.BooleanField(default=False)),
                ('change', models.BooleanField(default=False)),
                ('mile', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('engine_type', model_utils.fields.StatusField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], default='Petrol', max_length=100, no_check_for_status=True)),
                ('transmission_type', model_utils.fields.StatusField(choices=[('automatic', 'automatic'), ('manual', 'manual')], default='automatic', max_length=100, no_check_for_status=True)),
                ('motor_v_type', model_utils.fields.StatusField(choices=[('0.5', '0.5'), ('0.6', '0.6'), ('0.7', '0.7'), ('0.8', '0.8'), ('0.9', '0.9'), ('1', '1'), ('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.5', '1.5'), ('1.6', '1.6'), ('1.7', '1.7'), ('1.8', '1.8'), ('1.9', '1.9'), ('2', '2'), ('2.1', '2.1'), ('2.2', '2.2'), ('2.3', '2.3'), ('2.4', '2.4'), ('2.5', '2.5'), ('2.6', '2.6'), ('2.7', '2.7'), ('2.8', '2.8'), ('2.9', '2.9'), ('3', '3'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('3.5', '3.5'), ('3.6', '3.6'), ('3.7', '3.7'), ('3.8', '3.8'), ('3.9', '3.9'), ('4', '4'), ('4.1', '4.1'), ('4.2', '4.2'), ('4.3', '4.3'), ('4.4', '4.4'), ('4.5', '4.5'), ('4.6', '4.6'), ('4.7', '4.7'), ('4.8', '4.8'), ('4.9', '4.9'), ('5', '5'), ('5.3', '5.3'), ('5.5', '5.5'), ('6', '6')], default='0.5', max_length=100, no_check_for_status=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport.transport')),
                ('body_type', model_utils.fields.StatusField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Cabriolet', 'Cabriolet'), ('Universal', 'Universal'), ('SUV', 'SUV'), ('Grand Tourer', 'Grand Tourer'), ('Crossover', 'Crossover'), ('Van', 'Van'), ('Pickup', 'Pickup'), ('Minivan', 'Minivan'), ('Minibus', 'Minibus'), ('Bus', 'Bus')], default='Sedan', max_length=100, no_check_for_status=True)),
                ('wheel_type', model_utils.fields.StatusField(choices=[('Left', 'Left'), ('Right', 'Right')], default='Left', max_length=100, no_check_for_status=True)),
                ('drive_unit_type', model_utils.fields.StatusField(choices=[('Front', 'Front'), ('Rear', 'Rear'), ('4x4', '4x4')], default='Front', max_length=100, no_check_for_status=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('transport.transport',),
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport.transport')),
                ('motor_engin_type', model_utils.fields.StatusField(choices=[('Inline Engines', 'Inline Engines'), ('Single Cylinder', 'Single Cylinder'), ('Parallel Twin', 'Parallel Twin'), ('Inline Triple&Four', 'Inline Triple&Four'), ('V-Engines', 'V-Engines'), ('V-Twin', 'V-Twin'), ('V-Four', 'V-Four'), ('Flat Engines', 'Flat Engines'), ('Flat 4', 'Flat 4'), ('Other', 'Other')], default='Inline Engines', max_length=100, no_check_for_status=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('transport.transport',),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport.transport')),
                ('truck_type', model_utils.fields.StatusField(choices=[('Tractor', 'Tractor'), ('Tow Truck', 'Tow Truck'), ('Fire Engine', 'Fire Engine'), ('Cement Mixer', 'Cement Mixer'), ('Tanker', 'Tanker'), ('Trailer', 'Trailer'), ('Car Transport', 'Car Transport'), ('Forklift', 'Forklift'), ('Excavator', 'Excavator'), ('Crane', 'Crane'), ('Road Roller', 'Road Roller'), ('Dump Truck', 'Dump Truck'), ('Bulldozer', 'Bulldozer'), ('Other', 'Other')], default='Tractor', max_length=100, no_check_for_status=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('transport.transport',),
        ),
        migrations.CreateModel(
            name='TruckImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='transport/truck_images/')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle_images', to='transport.truck')),
            ],
        ),
        migrations.CreateModel(
            name='MotorcycleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='transport/motorcycle_images/')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle_images', to='transport.motorcycle')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='transport/car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='transport.car')),
            ],
        ),
    ]
