# Generated by Django 4.0.3 on 2022-04-12 13:50

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
                ('activity_field_type', model_utils.fields.StatusField(choices=[('Advocacy&LegalAdvice', 'Advocacy&LegalAdvice'), ('Finance&Banking', 'Finance&Banking'), ('Education', 'Education'), ('IT&Software', 'IT&Software'), ('Design&Creativity', 'Design&Creativity'), ('Business&StrategicManagement', 'Business&StrategicManagement'), ('Sales', 'Sales'), ('Merchandising&Retailing', 'Merchandising&Retailing'), ('Marketing&Product Management', 'Marketing&Product Management'), ('Health', 'Health'), ('Beauty&Care', 'Beauty&Care'), ('Entertainment&Activities', 'Entertainment&Activities'), ('Logistics&Transport', 'Logistics&Transport'), ('Restaurant&Accommodation', 'Restaurant&Accommodation'), ('Textile', 'Textile'), ('Agriculture&Livestock', 'Agriculture&Livestock'), ('Protection and Security', 'Protection and Security'), ('PartTime&AdditionalJobs', 'PartTime&AdditionalJobs')], default='Advocacy&LegalAdvice', max_length=100, no_check_for_status=True)),
                ('experience', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job.job')),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('job.job',),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job.job')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('job.job',),
        ),
        migrations.CreateModel(
            name='VacancyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='job/vacancy_images/')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_images', to='job.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='job/resume_images/')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_images', to='job.resume')),
            ],
        ),
    ]
